### ISSUE TITLE
Article cover images

### ISSUE THREAD

**Issue by bdukes** [bdukes/out-of-our-minds#44]
@nikkidukes We planned to have a "cover" image for each article, can you pick some out?

**Comment by bdukes** [comment]
At this point, none of [the four articles](https://github.com/bdukes/out-of-our-minds/tree/main/content/articles) have a cover image. It could help to have a generic fallback image, or we could just decide that we want every article to have a unique image (or maybe category-specific fallbacks?)

**Comment by nikkidukes** [comment]
On that list of 4, the top 3 have included images, so I thought those would
include a cover image.
I like the idea of category fallbacks, but many will fall into multiple
categories, so how do we decide which one to choose?

**Comment by nikkidukes** [comment]
And for the story at the library, maybe use a section of this stack (turned
horizontal?)
https://photos.app.goo.gl/XaJNSynRSuWUA5yUA
