### ISSUE TITLE
Articles & Store banner images

### ISSUE THREAD

**Issue by bdukes** [bdukes/out-of-our-minds#45]
@nikkidukes I believe that we intended for the Articles and Store banners on [the homepage](https://practical-colden-4953c3.netlify.app/) to have background images. Can you create or find some images to use there?

**Comment by nikkidukes** [comment]
I had planned to use photos from Casey's photo shoot that hasn't happened
yet. So I might need to take some or think through that better. What would
you imagine are the kinds of photos to use for that/content?

**Comment by bdukes** [comment]
@nikkidukes I'm thinking of something that's primarily visual texture. For _Articles_ maybe it could communicate "family" or "reading", and for _Store_ maybe something that looks like a visual planner or a collection of papers (or social stories?)

**Comment by bdukes** [comment]
@nikkidukes how does this look? https://64f659cef7fa10281b39407e--practical-colden-4953c3.netlify.app/

**Comment by nikkidukes** [comment]
I think i like it. maybe the font is too little or needs to be in caps or
something, though.
